/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.Comida;
import Persistencia.ComidaData;
import javax.swing.JOptionPane;

/**
 *
 * @author Ezequiel
 */
public class VistaComida extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaComida
     */
    Comida comidaActual = null;
    ComidaData cd = new ComidaData();

    public VistaComida() {
        initComponents();
        cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jLID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFCalorias_por_100g = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCBTipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADetalle = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jBNuevo = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();

        setClosable(true);

        jLID.setText("ID: --");

        jLabel2.setText("Nombre:");

        jTFNombre.setEnabled(false);

        jLabel3.setText("Calorias por 100g:");

        jTFCalorias_por_100g.setEnabled(false);

        jLabel4.setText("Tipo:");

        jCBTipo.setEnabled(false);

        jTADetalle.setColumns(20);
        jTADetalle.setRows(5);
        jTADetalle.setEnabled(false);
        jScrollPane1.setViewportView(jTADetalle);

        jLabel5.setText("Detalle:");

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.setEnabled(false);
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLID)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jTFCalorias_por_100g, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jCBTipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(34, 34, 34)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jBNuevo, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jBBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jBGuardar, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLID)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFCalorias_por_100g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jBGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(jBBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(jBNuevo)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        comidaActual = null;
        limpiarCampos();
        activarCampos();
        jBGuardar.setEnabled(true);
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        String entrada = JOptionPane.showInputDialog(this, "Ingrese el nombre completo de la comida");
        comidaActual = cd.buscarComidaPorNombre(entrada);
        if (comidaActual != null) {
            jLID.setText("ID: " + comidaActual.getId_comida());
            jTFNombre.setText(comidaActual.getNombre());
            jTFCalorias_por_100g.setText(String.valueOf(comidaActual.getCalorias_por_100g()));
            jTADetalle.setText(comidaActual.getDetalle());
            String tipoComida = comidaActual.getTipo();
            for (int i = 0; i < jCBTipo.getItemCount(); i++) {
                Object item = jCBTipo.getItemAt(i);
                if (item != null && item.toString().equalsIgnoreCase(tipoComida)) {
                    jCBTipo.setSelectedIndex(i);
                    break;
                }
            }
            activarCampos();
            jBGuardar.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Paciente no encontrado");
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        try {
            String nombre = jTFNombre.getText();
            Integer calorias_por_100g = Integer.valueOf(jTFCalorias_por_100g.getText());
            String tipo = String.valueOf(jCBTipo.getSelectedItem());
            String detalle = jTADetalle.getText();
            if (comidaActual != null) {
                comidaActual.setNombre(nombre);
                comidaActual.setCalorias_por_100g(calorias_por_100g);
                comidaActual.setTipo(tipo);
                comidaActual.setDetalle(detalle);
                cd.modificarComida(comidaActual);
            } else {
                comidaActual = new Comida();
                comidaActual.setNombre(nombre);
                comidaActual.setCalorias_por_100g(calorias_por_100g);
                comidaActual.setTipo(tipo);
                comidaActual.setDetalle(detalle);
                cd.guardarComida(comidaActual);
            }
            jLID.setText("ID: " + comidaActual.getId_comida());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error al ingresar los tipos de datos, revise");
        }
    }//GEN-LAST:event_jBGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JComboBox<String> jCBTipo;
    private javax.swing.JLabel jLID;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTADetalle;
    private javax.swing.JTextField jTFCalorias_por_100g;
    private javax.swing.JTextField jTFNombre;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo() {
        jCBTipo.addItem(null);
        jCBTipo.addItem("Desayuno");
        jCBTipo.addItem("Snack");
        jCBTipo.addItem("Almuerzo");
        jCBTipo.addItem("Merienda");
        jCBTipo.addItem("Cena");
    }

    private void limpiarCampos() {
        jLID.setText("ID: --");
        jTFNombre.setText("");
        jTFCalorias_por_100g.setText("");
        jCBTipo.setSelectedItem(0);
        jTADetalle.setText("");
    }

    private void activarCampos() {
        jTFNombre.setEnabled(true);
        jTFCalorias_por_100g.setEnabled(true);
        jCBTipo.setEnabled(true);
        jTADetalle.setEnabled(true);
    }
}
