/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.*;
import Persistencia.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Ezequiel
 */
public class VistaGenerarDieta extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaGenerarDieta
     */
    private DietaData dietaData;
    private MenuDiarioData menuData;
    private RenglonMenuData renglonData;
    private ComidaData comidaData;
    private PacienteData pacienteData;
    private List<Paciente> listaPaciente;

    public VistaGenerarDieta() {
        initComponents();
        dietaData = new DietaData();
        menuData = new MenuDiarioData();
        renglonData = new RenglonMenuData();
        comidaData = new ComidaData();
        pacienteData = new PacienteData();
        listaPaciente = pacienteData.listarPacientes();
        cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFprohibido = new javax.swing.JTextField();
        jCBpacientes = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTFdias = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBGenerar = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Nombre de la dieta:");

        jTFnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Alimentos que no quiere en la dieta:");

        jLabel4.setText("Cantidad de dias que tiene que durar la dieta:");

        jLabel3.setText("Paciente que desea generar la dieta:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jTFnombre)
                        .addComponent(jLabel2)
                        .addComponent(jTFprohibido, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                    .addComponent(jCBpacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTFdias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFprohibido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFdias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBpacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBGenerar.setText("Generar");
        jBGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBGenerar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBGenerar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnombreActionPerformed

    private void jBGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGenerarActionPerformed
      try{  
        String nombre = jTFnombre.getText();
        String prohibidos = jTFprohibido.getText();
        Integer dia = Integer.valueOf(jTFdias.getText());
        Paciente paciente = (Paciente) jCBpacientes.getSelectedItem();
    
    if (nombre.isEmpty() || prohibidos.isEmpty() || dia == 0 || paciente == null) {
        JOptionPane.showMessageDialog(null, "Complete todos los campos");
        return;
    } 
    
    Dieta dieta = new Dieta();
    dieta.setNombre(nombre);
    dieta.setPaciente(paciente);
    dietaData.guardarDieta(dieta);
    
    String[] alimentosProhibidos = prohibidos.split(",");
    List<String> alimentosProhibidosList = Arrays.asList(alimentosProhibidos);
    
    for (int i = 0; i < dia; i++) {
        MenuDiario menu = new MenuDiario();
        menu.setDia(i + 1);
        menu.setCalorias(2000); 
        menu.setDieta(dieta);
        menuData.guardarMenuDiario(menu);
        
        List<Comida> comidasDisponibles = comidaData.filtrarPorAlimentosProhibidos(alimentosProhibidosList);
        
        for (int j = 0; j < 5; j++) {
            RenglonMenu renglon = new RenglonMenu();
            renglon.setMenu_diario(menu);
            renglon.setComida(elegirComidaAleatoria(comidasDisponibles));
            renglon.setCantidad_gramos(100);
            renglon.setSubtotal_calorias(50);
            renglonData.guardarRenglonMenu(renglon);
        }
    } JOptionPane.showConfirmDialog(this, "Dieta generada exitosamente");
      } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jBGenerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGenerar;
    private javax.swing.JComboBox<Paciente> jCBpacientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFdias;
    private javax.swing.JTextField jTFnombre;
    private javax.swing.JTextField jTFprohibido;
    // End of variables declaration//GEN-END:variables
    private Comida elegirComidaAleatoria(List<Comida> comidas) {
        return comidas.get((int) (Math.random() * comidas.size()));
    }
    private void cargarCombo(){
        for (Paciente paciente : listaPaciente) {
            jCBpacientes.addItem(paciente);
        }
    }
}
