/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.Paciente;
import Persistencia.PacienteData;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class VistaListarPorIMC extends javax.swing.JInternalFrame {

    PacienteData pd = new PacienteData();
    DefaultTableModel modelo;
    /**
     * Creates new form VistaListarPorIMC
     */
    public VistaListarPorIMC() {
        initComponents();
        modelo = new DefaultTableModel();
        cargarTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Listar pacientes");
        setPreferredSize(new java.awt.Dimension(510, 355));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Lista de todos los pacientes segun su Indice de Masa Corporal (IMC):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 102, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
    private void cargarTable() {
        String[] columnas = {"ID", "Nombre", "Edad", "Altura", "Peso Actual", "IMC","normal","sobrepeso"};
        modelo.setColumnIdentifiers(columnas);
        List<Paciente> listaPacientes = pd.listarPacientes();
        for (Paciente paciente : listaPacientes) {
            float altura = paciente.getAltura();
            float pesoA = paciente.getPeso_actual();
            float imc = pesoA / (altura * altura);

            String normal = (imc < 25) ? "Sí" : "No";
            String sobrepeso = (imc >= 25) ? "Sí" : "No";
            Object[] fila = {
                paciente.getId_paciente(),
                paciente.getNombre(),
                paciente.getEdad(),
                altura,
                pesoA,
                imc,
                normal,
                sobrepeso
            };
            modelo.addRow(fila);
        }
        jTable1.setModel(modelo);
    }
}
