/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;
import com.formdev.flatlaf.intellijthemes.FlatGradiantoNatureGreenIJTheme;
/**
 *
 * @author Ezequiel
 */
public class VistaGeneral extends javax.swing.JFrame {

    /**
     * Creates new form VistaGeneral
     */
    public VistaGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMPacientes = new javax.swing.JMenu();
        jMGuardarPaciente = new javax.swing.JMenuItem();
        jMIComparar = new javax.swing.JMenuItem();
        jMIListar = new javax.swing.JMenuItem();
        jMIListaIMC = new javax.swing.JMenuItem();
        jMICargar = new javax.swing.JMenuItem();
        jMComidas = new javax.swing.JMenu();
        jMGuardarComida = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMDietas = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMMenus_diarios = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nutricionista");
        setPreferredSize(new java.awt.Dimension(620, 524));
        escritorio.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        jMenuBar1.setName(""); // NOI18N

        jMPacientes.setText("Pacientes");

        jMGuardarPaciente.setText("Guardar/Modificar paciente");
        jMGuardarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGuardarPacienteActionPerformed(evt);
            }
        });
        jMPacientes.add(jMGuardarPaciente);

        jMIComparar.setText("Comparar peso");
        jMIComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICompararActionPerformed(evt);
            }
        });
        jMPacientes.add(jMIComparar);

        jMIListar.setText("Listar pacientes que no llegaron");
        jMIListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIListarActionPerformed(evt);
            }
        });
        jMPacientes.add(jMIListar);

        jMIListaIMC.setText("Listar pacientes por IMC");
        jMIListaIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIListaIMCActionPerformed(evt);
            }
        });
        jMPacientes.add(jMIListaIMC);

        jMICargar.setText("Cargar peso y finalizar dieta");
        jMICargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICargarActionPerformed(evt);
            }
        });
        jMPacientes.add(jMICargar);

        jMenuBar1.add(jMPacientes);

        jMComidas.setText("Comidas");

        jMGuardarComida.setText("Guardar/Modificar comida");
        jMGuardarComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGuardarComidaActionPerformed(evt);
            }
        });
        jMComidas.add(jMGuardarComida);

        jMenuItem5.setText("Listar todas comidas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMComidas.add(jMenuItem5);

        jMenuBar1.add(jMComidas);

        jMDietas.setText("Dietas");

        jMenuItem2.setText("Guardar/modificar dieta");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMDietas.add(jMenuItem2);

        jMenuItem6.setText("Generar dieta automaticamente");
        jMDietas.add(jMenuItem6);

        jMenuBar1.add(jMDietas);

        jMMenus_diarios.setText("Menus Diarios");

        jMenuItem1.setText("Guardar/Modificar menu diario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMMenus_diarios.add(jMenuItem1);

        jMenuItem3.setText("Calcular calorias del dia");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMMenus_diarios.add(jMenuItem3);

        jMenuItem4.setText("Imprimir menu diario");
        jMMenus_diarios.add(jMenuItem4);

        jMenuBar1.add(jMMenus_diarios);

        jMenu1.setText("Renglon de menu");

        jMenuItem7.setText("Guardar/ modificar renglon de menu");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Imprimir renglon");
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMGuardarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGuardarPacienteActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaPaciente vp = new VistaPaciente();
        escritorio.add(vp);
        escritorio.moveToFront(vp);
        vp.setVisible(true);
    }//GEN-LAST:event_jMGuardarPacienteActionPerformed

    private void jMGuardarComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGuardarComidaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaComida vc = new VistaComida();
        escritorio.add(vc);
        escritorio.moveToFront(vc);
        vc.setVisible(true);
    }//GEN-LAST:event_jMGuardarComidaActionPerformed

    private void jMICompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICompararActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaCompararPeso vc = new VistaCompararPeso();
        escritorio.add(vc);
        escritorio.moveToFront(vc);
        vc.setVisible(true);
    }//GEN-LAST:event_jMICompararActionPerformed

    private void jMIListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIListarActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaListarPacientes vl = new VistaListarPacientes();
        escritorio.add(vl);
        escritorio.moveToFront(vl);
        vl.setVisible(true);
    }//GEN-LAST:event_jMIListarActionPerformed

    private void jMICargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICargarActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaCargarPesoYFinalizar vc = new VistaCargarPesoYFinalizar();
        escritorio.add(vc);
        escritorio.moveToFront(vc);
        vc.setVisible(true);
    }//GEN-LAST:event_jMICargarActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaListarComida vlc = new VistaListarComida();
        escritorio.add(vlc);
        escritorio.moveToFront(vlc);
        vlc.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaRenglonDeMenu vrm = new VistaRenglonDeMenu();
        escritorio.add(vrm);
        escritorio.moveToFront(vrm);
        vrm.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaDieta vd = new VistaDieta();
        escritorio.add(vd);
        escritorio.moveToFront(vd);
        vd.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaMenuDiario vm = new VistaMenuDiario();
        escritorio.add(vm);
        escritorio.moveToFront(vm);
        vm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMIListaIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIListaIMCActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaListarPorIMC vimc = new VistaListarPorIMC();
        escritorio.add(vimc);
        escritorio.moveToFront(vimc);
        vimc.setVisible(true);
    }//GEN-LAST:event_jMIListaIMCActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaCalcularCalorias vcc = new VistaCalcularCalorias();
        escritorio.add(vcc);
        escritorio.moveToFront(vcc);
        vcc.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatGradiantoNatureGreenIJTheme.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaGeneral().setVisible(true);
            }
        });
        FlatGradiantoNatureGreenIJTheme.setup();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMComidas;
    private javax.swing.JMenu jMDietas;
    private javax.swing.JMenuItem jMGuardarComida;
    private javax.swing.JMenuItem jMGuardarPaciente;
    private javax.swing.JMenuItem jMICargar;
    private javax.swing.JMenuItem jMIComparar;
    private javax.swing.JMenuItem jMIListaIMC;
    private javax.swing.JMenuItem jMIListar;
    private javax.swing.JMenu jMMenus_diarios;
    private javax.swing.JMenu jMPacientes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    // End of variables declaration//GEN-END:variables
}
